### ISSUE TITLE
No usdt visibility in test app on linux

### ISSUE THREAD

**Issue by viraptor** [oxidecomputer/usdt#22]
Given the `dtrace` usage in README I'm not sure if this is just not implemented on Linux, but I can't see the macros exposed at all.

I've compiled the test app (probe-test-macro) on linux with kernel 5.13 and used rust nightly-2021-06-17.

Everything seems to be running ok, but the probes are not exposed. I see other entries just fine  - for example:

```
usdt:/proc/42722/root/usr/lib64/libpthread-2.33.so:libpthread:mutex_entry
```

But the start/stop probes are not there.

**Comment by ahl** [comment]
This is only intended to be run on systems that support DTrace (which includes flavors of Linux with DTrace). We'd happily take a look at a PR for support for some other tracing system or you can check out https://crates.io/crates/sonde

**Comment by bnaecker** [comment]
Closing this for now. Please feel free to comment again, or open a new PR if you'd like to add Linux support.

**Comment by VorpalBlade** [comment]
https://crates.io/crates/probe is another possibility for Linux, which unlike sonde has documentation comments. It is the more popular option as well. It also more closely matches the `sys/sdt.h` approach used on Linux: no need to register probes, no need for a separate definition file. Instead special inline assembler is emitted, including to a special `.notes` section in the ELF file. It is up to the tracing program to use that info to tell the kernel to patch the libaries or binaries in memory to enable the tracing.

All that said, I would be interested in seeing Linux support in **this** crate, so that tokio-dtrace, diesel-dtrace etc can be of use to a wider group of people. A cfg or feature flag would seem to be a reasonable way to switch between the two implementations of UDST tracepoints (unless it is possible to make a polyglot tracepoint that works with either? I don't know the anatomy of the dtrace tracepoints enough to say though, but it would be cool.)
