### ISSUE TITLE
Do we want to have a rust-toolchain.toml file in the repo?

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/usdt#269]
Currently, this repo has a rust-toolchain.toml file in it, pinning the version to 1.75.0:

https://github.com/oxidecomputer/usdt/blob/d4b8090f2bf8527bf6aa0c43e94063ee68647c41/rust-toolchain.toml#L1

Is this something we'd still like to carry around?

* For binaries it makes sense to have such a file, but usdt is primarily a library.
* usdt needed nightly features for a long time, but it no longer does (and #267 removes all the nightly code).
* Rust is "append-only" and new versions very rarely break old code.

Would it make sense to remove the rust-toolchain.toml file, and let CI find issues with the MSRV?

**Comment by bnaecker** [comment]
One nice reason is to ensure that we're always testing locally with the CI version. That matters for the `trybuild` tests mostly, where there can be small variations in the compiler output that aren't that meaningful. I don't feel too strongly though, since practically-speaking most contributors will know how to read and diagnose those errors in CI, even if they don't see them locally without building against that specific toolchain.

**Comment by sunshowers** [comment]
Thank you! Okay, yeah, the `trybuild` tests are a great reason to pin the Rust toolchain. I think in that case I'll pin the version to 1.80, and also ensure that CI (minus the trybuild tests) runs on the MSRV.

**Comment by sunshowers** [comment]
Rationale added here: https://github.com/oxidecomputer/usdt/blob/5a4bc0ec0ca04d3e1a38d7fe0ef16e3ac50d417d/rust-toolchain.toml#L2
