### ISSUE TITLE
have you seen this probe?

### ISSUE THREAD

**Issue by rzezeski** [oxidecomputer/usdt#61]
While working oxidecomputer/opte#145 I ran into a couple of interesting issues with usdt. The first issue has to do with macOS and the seeming inability to pass a 6th arg. The second one, the one I'm more concerned with and the subject of this title, is the disappearance of probe firings on illumos. I'm only going to focus on the illumos issue in this ticket, but I mention the macOS issue in case it is somehow related (and I'll file a separate issue for it).

## Background

In production OPTE runs in the kernel via the xde device driver, and thus makes use of kernel SDT probes. However, it can be very useful during development to have USDT equivalent versions of these probes when running unit tests. I did this by writing wrapper functions/methods for these probe sites and then used `cfg_if!` to switch between SDT/USDT depending on feature flags. These USDT probes are defined in `opte/src/lib.rs`. The one I want to focus on in particular is the `port__process__return` probe, used in `opte/src/engine/port.rs`: anytime a port processes a packet, this probe should fire.

## Issue

When running the OPTE unit tests on illumos I see the `port-process-return` probe fire a varying number of times across runs; but it should fire the **same** number of times for **each** run. See the excerpt below, where each run was a full `cargo test` run.

```
rpz@midgar:~/src/oxidecomputer/opte/dtrace$ pfexec dtrace -Zn 'port-process-return { trace(ar
g5); }'
dtrace: description 'port-process-return ' matched 0 probes
CPU     ID                    FUNCTION:NAME

--- RUN 1 ---
 14  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          35377040
  8  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          35814608


--- RUN 2 ---
  0  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          26270288
  2  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          26291088
  0  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          26270288
  4  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          26623376
 13  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          26422544
  0  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          26291216
 13  85644 _ZN4opte6engine4port4Port25port_process_return_probe17hf7c493aa9c30a8d2E:port-process-return          26422544
```

Not only is the number of times the probe fired different, but in both cases it seems the probe fired way less than it should. If I trace the same probe on macOS it looks like it always fires 16 times.

## Reproduce

1. Clone opte onto your helios/illumos box; checkout the `opte-143-set-fw-rules` branch.
2. In one window trace the `port-process-return` probe.
```
$ pfexec dtrace -Zn 'port-process-return { trace(arg5); }'
```
3. In another window run the OPTE unit tests.
```
$ cd opte
$ cargo test --features usdt
```

**Comment by bnaecker** [comment]
Ok, I believe I understand this issue. On macOS, we use the system compiler to generate the probe metadata, and the runtime linker does the work of actually registering the probes with the DTrace kernel module. On illumos, we actually construct the metadata ourselves, and then issue an `ioctl(2)` to send that to the kernel. This is what the `usdt::register_probes` function does.

If you run the tests on `illumos` with `--test-threads 1`, the probe fires 7 times consistently. Still not 16 as it should, but it's consistent. Looking for the call to `register_probes`, we find it [here](https://github.com/oxidecomputer/opte/blob/e5bcaa0c6e4b7b39fd9167be235a4ac1153869b4/opte/src/engine/int_test.rs#L285). If we move that to the `api::encap::bad_vni` test [here](https://github.com/oxidecomputer/opte/blob/e5bcaa0c6e4b7b39fd9167be235a4ac1153869b4/opte/src/api/encap.rs#L98), which is the first test to run when we use a single thread, then we get 12 probes firing:


```
  2  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35946064
  2  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797584
  2  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797584
  2  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797584
  2  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35834704
  2  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797936
  2  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35946064
  7  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35834768
  7  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797584
  7  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797584
  7  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35834960
  7  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797776
  7  93995 _ZN4opte6engine4port4Port25port_process_return_probe17h3de444539d1667f0E:port-process-return          35797776
```

I'm not sure where you got 16, since 12 is the same number I see when running the tests on my mac machine.

Assuming 12 is the expected number, I'm not sure what can be done about this. We've tried [to document clearly](https://docs.rs/usdt/latest/usdt/#registration) that the probes will not be available until `register_probes` is called. Early in the implementation of the crate, we discussed hacks to automatically register the probes when the program is loaded. We decided against that, since a cross-platform, foolproof solution would be difficult to achieve, especially given that Rust explicitly [lacks any concept of code running prior to main](https://internals.rust-lang.org/t/from-life-before-main-to-common-life-in-main/16006).

The best we can do at this point is just require that consumers call `register_probes` "early enough". This is obviously difficult in threaded code or tests, where it's not always obvious what runs first. One strategy is a macro that decorates each test, ensuring it calls the `register_probes` function. That's not great, and I wish we had better answers. Let me know if you have other ideas!

**Comment by bnaecker** [comment]
Another option, rather than a macro, is a `lazy_static` that basically just calls the `register_probes` function. You could then deref that in each test, which would be sure it runs. The function is thread-safe.

**Comment by rzezeski** [comment]
> I'm not sure where you got 16, since 12 is the same number I see when running the tests on my mac machine.

My bad I was using `-o <file>` option and then using `wc -l` on that, but that includes some other stuff. Though if I use grep to only include probe firings I get 13.

> We've tried [to document clearly](https://docs.rs/usdt/latest/usdt/#registration) that the probes will not be available until register_probes is called.

Haha, well I feel dumb because I literally just thought of this the other day and forgot to come back to it. When I first wrote these usdt probes I just stuck the `reigster_probes` in a test and moved along. I meant to come back around to that to make sure it's initialized before any tests run, but that never happened.

So in any event it seems this is a non-issue. Sorry for the confusion!

**Comment by bnaecker** [comment]
No worries at all, this has been an annoying limitation since day one! Glad we figured it out.
